name: einayaaminah
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.11.0
  flutter_app_name: ^0.1.0
  lottie: ^2.6.0
  flutter_onboarding_slider: ^1.0.10
  crypto: ^3.0.3
  http: ^1.1.0
  flutter_appauth: ^6.0.2
  supabase_flutter: ^1.10.14
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  google_mlkit_text_recognition: ^0.10.0
  image_picker: ^1.0.4
  image_cropper: ^5.0.0
  shimmer: ^3.0.0
  supabase: ^1.11.3
  universal_platform: ^1.0.0+1
  equatable: ^2.0.5
  google_fonts: ^5.1.0
  syncfusion_flutter_pdfviewer: ^22.2.12
  flutter_localizations:
    sdk: flutter

  flutter_highlight: ^0.7.0
  shared_preferences: ^2.2.1
  intl: ^0.18.1

  liquid_pull_to_refresh: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/imgs/
    - assets/icons/
    - assets/animation/
    - assets/pdfs/

flutter_app_name:
  name: "Einaya Aminah"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/imgs/app_logo.png"
  min_sdk_android: 22
  web:
    generate: true
    image_path: "assets/imgs/launch_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/imgs/app_logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/imgs/app_logo.png"
flutter_intl:
  enabled: true
